"""Adding imobiliaria table

Revision ID: 0a3a629da501
Revises: 608a8eeb1ff8
Create Date: 2016-08-24 01:17:03.099671

"""

# revision identifiers, used by Alembic.
revision = '0a3a629da501'
down_revision = '608a8eeb1ff8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imobiliarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('imoveis', sa.Column('imobiliaria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'imoveis', 'imobiliarias', ['imobiliaria_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imoveis', type_='foreignkey')
    op.drop_column('imoveis', 'imobiliaria_id')
    op.drop_table('imobiliarias')
    ### end Alembic commands ###
