"""Creating model Fogao

Revision ID: 11795a3e7b4f
Revises: e06efd93e325
Create Date: 2016-08-19 00:11:33.298281

"""

# revision identifiers, used by Alembic.
revision = '11795a3e7b4f'
down_revision = 'e06efd93e325'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fogoes',
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('link_loja', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_bocas', sa.Integer(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fogoes')
    ### end Alembic commands ###
