"""Creating MaquinaDeLavar model

Revision ID: 3d8176270b18
Revises: 9dfbfa3f09b1
Create Date: 2016-08-30 14:55:44.349730

"""

# revision identifiers, used by Alembic.
revision = '3d8176270b18'
down_revision = '9dfbfa3f09b1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquinas_de_lavar',
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('preco_parcelado', sa.Float(), nullable=True),
    sa.Column('preco_a_vista', sa.Float(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('largura', sa.Float(), nullable=True),
    sa.Column('comprimento', sa.Float(), nullable=True),
    sa.Column('link_loja', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacidade', sa.Float(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maquinas_de_lavar')
    ### end Alembic commands ###
