"""Adding link field to Imovel table

Revision ID: 5dd905265cfb
Revises: 81d2bec8e9ba
Create Date: 2016-08-23 16:58:17.181515

"""

# revision identifiers, used by Alembic.
revision = '5dd905265cfb'
down_revision = '81d2bec8e9ba'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('link', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imoveis', 'link')
    ### end Alembic commands ###
