"""Adding more fields to Imovel

Revision ID: 608a8eeb1ff8
Revises: 787642ad0e6f
Create Date: 2016-08-24 00:25:04.008375

"""

# revision identifiers, used by Alembic.
revision = '608a8eeb1ff8'
down_revision = '787642ad0e6f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('chuveiro', sa.String(), nullable=True))
    op.add_column('imoveis', sa.Column('tem_elevador', sa.Boolean(), nullable=True))
    op.add_column('imoveis', sa.Column('tem_portaria', sa.Boolean(), nullable=True))
    op.add_column('imoveis', sa.Column('tem_salao_festas', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imoveis', 'tem_salao_festas')
    op.drop_column('imoveis', 'tem_portaria')
    op.drop_column('imoveis', 'tem_elevador')
    op.drop_column('imoveis', 'chuveiro')
    ### end Alembic commands ###
