"""Adding more fields to Imovel

Revision ID: 787642ad0e6f
Revises: 404a39e8d0a6
Create Date: 2016-08-23 23:36:14.820495

"""

# revision identifiers, used by Alembic.
revision = '787642ad0e6f'
down_revision = '404a39e8d0a6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('andar', sa.Integer(), nullable=True))
    op.add_column('imoveis', sa.Column('codigo_imovel', sa.Integer(), nullable=True))
    op.add_column('imoveis', sa.Column('nivel_barulho', sa.Integer(), nullable=True))
    op.add_column('imoveis', sa.Column('nota', sa.Integer(), nullable=True))
    op.add_column('imoveis', sa.Column('sol', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imoveis', 'sol')
    op.drop_column('imoveis', 'nota')
    op.drop_column('imoveis', 'nivel_barulho')
    op.drop_column('imoveis', 'codigo_imovel')
    op.drop_column('imoveis', 'andar')
    ### end Alembic commands ###
