"""Adding marca field to ItemDespensa

Revision ID: 7bcd5c765b72
Revises: 87338b9c7a3a
Create Date: 2016-08-24 11:09:54.273957

"""

# revision identifiers, used by Alembic.
revision = '7bcd5c765b72'
down_revision = '87338b9c7a3a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_despensa', sa.Column('marca', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_despensa', 'marca')
    ### end Alembic commands ###
