"""Adding telefone field for imovel and imobiliaria

Revision ID: 7efb919b0ccb
Revises: 0a3a629da501
Create Date: 2016-08-24 01:19:17.663074

"""

# revision identifiers, used by Alembic.
revision = '7efb919b0ccb'
down_revision = '0a3a629da501'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imobiliarias', sa.Column('telefone', sa.Integer(), nullable=True))
    op.add_column('imoveis', sa.Column('telefone', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imoveis', 'telefone')
    op.drop_column('imobiliarias', 'telefone')
    ### end Alembic commands ###
