"""Adding more fields to imovel table

Revision ID: 808d3a41cca7
Revises: 45c42c821ae0
Create Date: 2016-08-24 02:18:08.695521

"""

# revision identifiers, used by Alembic.
revision = '808d3a41cca7'
down_revision = '45c42c821ae0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('comentarios', sa.String(), nullable=True))
    op.add_column('imoveis', sa.Column('farmacia', sa.Boolean(), nullable=True))
    op.add_column('imoveis', sa.Column('mercado', sa.Boolean(), nullable=True))
    op.add_column('imoveis', sa.Column('posto_gasolina', sa.Boolean(), nullable=True))
    op.add_column('imoveis', sa.Column('shopping', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imoveis', 'shopping')
    op.drop_column('imoveis', 'posto_gasolina')
    op.drop_column('imoveis', 'mercado')
    op.drop_column('imoveis', 'farmacia')
    op.drop_column('imoveis', 'comentarios')
    ### end Alembic commands ###
