"""Adding fields to imovel table

Revision ID: 81d2bec8e9ba
Revises: fb9592cd6c26
Create Date: 2016-08-23 16:55:32.869776

"""

# revision identifiers, used by Alembic.
revision = '81d2bec8e9ba'
down_revision = 'fb9592cd6c26'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('endereco', sa.String(), nullable=True))
    op.add_column('imoveis', sa.Column('numero_dormitorios', sa.Integer(), nullable=True))
    op.add_column('imoveis', sa.Column('tem_garagem', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imoveis', 'tem_garagem')
    op.drop_column('imoveis', 'numero_dormitorios')
    op.drop_column('imoveis', 'endereco')
    ### end Alembic commands ###
