"""Creating ItemDespensa e GrupoDespensa tables

Revision ID: 87338b9c7a3a
Revises: 934903613f62
Create Date: 2016-08-24 11:06:36.568960

"""

# revision identifiers, used by Alembic.
revision = '87338b9c7a3a'
down_revision = '934903613f62'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_despensa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_despensa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_despensa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_despensa')
    op.drop_table('grupos_despensa')
    ### end Alembic commands ###
