"""Creating guardas_roupas and sofas tables

Revision ID: 934903613f62
Revises: 75a5da1f2676
Create Date: 2016-08-24 08:24:29.642828

"""

# revision identifiers, used by Alembic.
revision = '934903613f62'
down_revision = '75a5da1f2676'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardas_roupas',
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('preco_parcelado', sa.Float(), nullable=True),
    sa.Column('preco_a_vista', sa.Float(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('largura', sa.Float(), nullable=True),
    sa.Column('comprimento', sa.Float(), nullable=True),
    sa.Column('link_loja', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_portas', sa.Integer(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sofas',
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('preco_parcelado', sa.Float(), nullable=True),
    sa.Column('preco_a_vista', sa.Float(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('largura', sa.Float(), nullable=True),
    sa.Column('comprimento', sa.Float(), nullable=True),
    sa.Column('link_loja', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_lugares', sa.Integer(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sofas')
    op.drop_table('guardas_roupas')
    ### end Alembic commands ###
