"""Creating Pergunta model

Revision ID: 9dfbfa3f09b1
Revises: fb3f9f00960f
Create Date: 2016-08-30 14:45:23.975401

"""

# revision identifiers, used by Alembic.
revision = '9dfbfa3f09b1'
down_revision = 'fb3f9f00960f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.String(), nullable=True),
    sa.Column('resposta', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perguntas')
    ### end Alembic commands ###
