"""Adding cor field to base item

Revision ID: bc44192812f4
Revises: 6c6848eba943
Create Date: 2016-08-23 15:57:38.185676

"""

# revision identifiers, used by Alembic.
revision = 'bc44192812f4'
down_revision = '6c6848eba943'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fogoes', sa.Column('cor', sa.String(), nullable=True))
    op.add_column('geladeiras', sa.Column('cor', sa.String(), nullable=True))
    op.add_column('microondas', sa.Column('cor', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microondas', 'cor')
    op.drop_column('geladeiras', 'cor')
    op.drop_column('fogoes', 'cor')
    ### end Alembic commands ###
