"""Adding onibus fields to imovel

Revision ID: bf62ce946645
Revises: 7efb919b0ccb
Create Date: 2016-08-24 01:22:25.912717

"""

# revision identifiers, used by Alembic.
revision = 'bf62ce946645'
down_revision = '7efb919b0ccb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('linha_onibus', sa.Boolean(), nullable=True))
    op.add_column('imoveis', sa.Column('parada_onibus', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imoveis', 'parada_onibus')
    op.drop_column('imoveis', 'linha_onibus')
    ### end Alembic commands ###
