"""Adding two separate fields for preco

Revision ID: d295d274577a
Revises: 05c71b4c3d54
Create Date: 2016-08-22 14:21:35.399100

"""

# revision identifiers, used by Alembic.
revision = 'd295d274577a'
down_revision = '05c71b4c3d54'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fogoes', sa.Column('preco_a_vista', sa.Float(), nullable=True))
    op.add_column('fogoes', sa.Column('preco_parcelado', sa.Float(), nullable=True))
    op.drop_column('fogoes', 'preco')
    op.add_column('geladeiras', sa.Column('preco_a_vista', sa.Float(), nullable=True))
    op.add_column('geladeiras', sa.Column('preco_parcelado', sa.Float(), nullable=True))
    op.drop_column('geladeiras', 'preco')
    op.add_column('microondas', sa.Column('preco_a_vista', sa.Float(), nullable=True))
    op.add_column('microondas', sa.Column('preco_parcelado', sa.Float(), nullable=True))
    op.drop_column('microondas', 'preco')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microondas', sa.Column('preco', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('microondas', 'preco_parcelado')
    op.drop_column('microondas', 'preco_a_vista')
    op.add_column('geladeiras', sa.Column('preco', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('geladeiras', 'preco_parcelado')
    op.drop_column('geladeiras', 'preco_a_vista')
    op.add_column('fogoes', sa.Column('preco', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('fogoes', 'preco_parcelado')
    op.drop_column('fogoes', 'preco_a_vista')
    ### end Alembic commands ###
