"""Initial database schema

Revision ID: e06efd93e325
Revises: 
Create Date: 2016-08-19 00:05:02.144999

"""

# revision identifiers, used by Alembic.
revision = 'e06efd93e325'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geladeiras',
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('link_loja', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geladeiras')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('lojas')
    ### end Alembic commands ###
