"""creating checklist_items table

Revision ID: e68770cd2bb2
Revises: 808d3a41cca7
Create Date: 2016-08-24 04:47:33.168340

"""

# revision identifiers, used by Alembic.
revision = 'e68770cd2bb2'
down_revision = '808d3a41cca7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('finalizado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_items')
    ### end Alembic commands ###
