"""Adding unidade field to ItemDespensa

Revision ID: fb3f9f00960f
Revises: e5c8fab2b858
Create Date: 2016-08-25 10:25:13.935888

"""

# revision identifiers, used by Alembic.
revision = 'fb3f9f00960f'
down_revision = 'e5c8fab2b858'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_despensa', sa.Column('unidade', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_despensa', 'unidade')
    ### end Alembic commands ###
