"""Creating imovel and bairro tables

Revision ID: fb9592cd6c26
Revises: bc44192812f4
Create Date: 2016-08-23 16:49:04.209954

"""

# revision identifiers, used by Alembic.
revision = 'fb9592cd6c26'
down_revision = 'bc44192812f4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bairros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('e_perigoso', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.Float(), nullable=True),
    sa.Column('bairro_id', sa.Integer(), nullable=True),
    sa.Column('valor_aluguel', sa.Float(), nullable=True),
    sa.Column('valor_condominio', sa.Float(), nullable=True),
    sa.Column('valor_iptu', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imoveis')
    op.drop_table('bairros')
    ### end Alembic commands ###
