"""Adding tipo column to Fogao

Revision ID: fc2dd305407f
Revises: 3d8176270b18
Create Date: 2016-08-30 15:41:43.152287

"""

# revision identifiers, used by Alembic.
revision = 'fc2dd305407f'
down_revision = '3d8176270b18'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE tipos_fogao AS ENUM ('N/A', 'Piso', 'Embutível', 'Cooktop à Gás', 'Cooktop Elétrico', 'Cooktop por Indução')")
    op.add_column('fogoes', sa.Column('tipo', sa.Enum('N/A', 'Piso', 'Embutível', 'Cooktop à Gás', 'Cooktop Elétrico', 'Cooktop por Indução', name='tipos_fogao'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fogoes', 'tipo')
    ### end Alembic commands ###
